---
title: "Data Exploration"
author: "Nour Al khoury, Rim Moussa (Team 3)"
date: "6/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

```{r echo = FALSE, message=FALSE, warning=FALSE}
library(stringr)
library(ggplot2)
library(patchwork)
library(dplyr)
library(ggrepel)
library(treemapify)
library(tidyverse)
```



# Load Data
```{r}
metadata = read.csv("data/metadata.csv")

```

# Exploratory Data Analysis

## Number of cells per donor
```{r}
# as.data.frame(table(metadata$external_donor_name_label)) %>%
#   ggplot(aes(x = reorder(Var1, -Freq), y = Freq, fill =metadata$donor_sex_label[match(Var1, metadata$external_donor_name_label)]))+
 metadata %>%
  ggplot(aes(x = factor(external_donor_name_label), fill=donor_sex_label)) +
  geom_bar(stat = "count") # stat = "count" is implied in the first example 


# g2 = metadata %>%
#   ggplot(aes(x = donor_sex_label, fill = donor_sex_label))+
#   geom_bar()

#g1 + g2 
```


# Cell type distribution
```{r}
#parse_type <- function(x) {str_extract(x, "L[1-6](a|b)?((/|-)[1-6])?(a|b)?")}
#metadata$layer <- sapply(metadata$cluster_label, parse_layer)
type_count = data.frame(table(metadata$cluster_label))

type_count %>% 
  ggplot(aes(y = Freq, x = Var1, label = Var1, fill=Var1)) +
  geom_bar(stat = "identity") +
  #geom_text_repel(max.overlaps = 20) +
  theme_minimal() +
  theme(legend.position = "None",
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +  
  labs(y = "Count",
       x = "Cell Type")
```

## Cell type distribtion per brain region
```{r}
df = data.frame(table(metadata$cluster_label))
df$region_label = rep('M1',nrow(df))
```

```{r}
ggplot(df, aes(area = Freq, fill = Var1,subgroup = region_label,
               label = paste(Var1, Freq, sep = "\n"))) +
  geom_treemap() +
  geom_treemap_text(colour = "white",
                    place = "centre",
                    size = 25) +
    geom_treemap_subgroup_text(place = "centre", grow = TRUE,
                             alpha = 0.25, colour = "black",
                             fontface = "italic") +
  theme(legend.position = "none")
```


## Class distribution of cells
```{r}
metadata %>% 
  ggplot(aes(x = class_label, group = class_label, fill=class_label)) + 
  geom_bar(stat = "count") # stat = "count" is implied in the first example 
```


## Number of cells per layer
Parsing cortical layer
```{r}
parse_layer <- function(x) {str_extract(x, "L[1-6](a|b)?((/|-)[1-6])?(a|b)?")}
metadata$layer <- sapply(metadata$cluster_label, parse_layer)
```


```{r}
metadata %>% 
  ggplot(aes(x = layer, group = layer, fill = layer)) + 
  geom_bar(stat = "count") # stat = "count" is implied in the first example 
```

# Post filtering

filter out ambiguous layers and non neuronal cell types
```{r}
DE_metadata = metadata %>%
  dplyr::filter(layer %in% c("L1", "L2", "L3", "L5", "L6"),
                ! class_label %in% "Non-Neuronal")
```


```{r}
DE_metadata %>% 
  ggplot(aes(x = layer, group = layer, fill = layer)) + 
  geom_bar(stat = "count")
```

```{r}
DE_metadata %>% 
  ggplot(aes(x = class_label, group = class_label, fill=class_label)) + 
  geom_bar(stat = "count")
```

```{r}
write.csv(DE_metadata, file = "data/metadata-fitlered.csv")
```


<!-- ### Fixing distribution -->
<!-- ```{r} -->
<!-- #layers.extended = data.frame() -->

<!-- for (row in 57725:nrow(metadata)){ -->
<!--   layers = strsplit(metadata$layer[row], "-") -->
<!--   start =  strtoi(str_replace(layers[[1]][1],'L', '')) -->

<!--   if (length(layers[[1]]) > 1) { -->
<!--     end = strtoi(layers[[1]][2])} -->
<!--   else{ -->
<!--     end = strtoi(start) -->
<!--   } -->
<!--   l = c() -->
<!--   df = data.frame() -->
<!--   for (i in start:end) { -->
<!--     l = c(l, i) -->
<!--     df = rbind(metadata[row,], df) -->
<!--   } -->
<!--   df$single_layer = l -->

<!--   layers.extended = rbind(layers.extended, df) -->
<!-- } -->
<!-- ``` -->

<!-- ```{r} -->
<!-- write.csv(layers.extended,"../data/layers_extended.csv", row.names = FALSE) -->
<!-- ``` -->


```{r eval=FALSE, include=FALSE}
layers.extended %>% 
  ggplot(aes(x = single_layer, group = factor(single_layer), fill = factor(single_layer))) + 
  geom_bar(stat = "count") # stat = "count" is implied in the first example 
```

```{python}
def read_pickle_file(file):
    pickle_data = pd.read_pickle(file)
    return pickle_data
```


```{r}
data = read.csv("../../../Applied Machine Learning/Projects/week9/data2.csv")
cols = read.csv("../../../Applied Machine Learning/Projects/week9/cols2.csv", header = FALSE)[,1]
```


```{r}
colnames(data) = cols
write.csv(data, file = "../../../Applied Machine Learning/Projects/week9/data-larger.csv")
```


```{r}
metadata = read.delim("../../../Applied Machine Learning/Projects/week9/a_MTBLS1129_LC-MS_positive_reverse-phase_metabolite_profiling.txt")
metadata2 = read.delim("../../../Applied Machine Learning/Projects/week9/m_MTBLS1129_LC-MS_positive_reverse-phase_metabolite_profiling_v2_maf.tsv")
```

```{r}
tmp = gsub(x = colnames(data), pattern = "\\.featureXML", replacement = "")

tmp2 =  gsub(x = colnames(data), pattern = "\\.mzML", replacement = "")
colnames(data) = tmp2

data2 = data %>%
  #dplyr::relocate(relocate(c("mz", "mzmin", "mzmax"," rt", "rtmin", "rtmax" ), .after = last_col()))
  dplyr::relocate(c(mz, mzmin, mzmax,rt, rtmin, rtmax), .after = last_col())

write.csv(data, file = "../../../Applied Machine Learning/Projects/week9/data-larger.csv")
metadata$`Include Sample` = metadata$Derived.Spectral.Data.File %in% tmp

metadata$Dilution = 100
  
new_metadata = metadata %>%
  dplyr::select(`Sample.Name`, `Derived.Spectral.Data.File`, `MS.Assay.Name`, Dilution,  `Include Sample`) %>%
  dplyr::mutate(`Derived.Spectral.Data.File` = gsub("\\.mzML", replacement = "", x = `Derived.Spectral.Data.File`),
                #`Derived.Spectral.Data.File` = gsub("mennormal", replacement = "", x = `Derived.Spectral.Data.File`)
                `MS.Assay.Name` = "Assay",
                SampleType = "Study Sample"
                )%>%
          
                #`Correction Batch` = sample(1:2, size = 19, replace = T),
                #`Derived.Spectral.Data.File` = paste0("data/",`Derived.Spectral.Data.File`),) 
  dplyr::rename(`Sample ID` = `Sample.Name`,
                `Sample File Name` = `Derived.Spectral.Data.File`,
                `AssayRole` = `MS.Assay.Name`) %>%
  dplyr::filter(`Include Sample`) %>%
  dplyr::mutate(`Correction Batch` =  NA) 

new_metadata$SampleType[grep(pattern = "^QC", x = new_metadata$`Sample ID`)] = "Study Pool"
new_metadata$AssayRole[grep(pattern = "^QC", x = new_metadata$`Sample ID`)] = "Precision Reference"


# data = data %>%
#   dplyr::select(c(mz, mzmin, mzmax,rt, rtmin, rtmax), new_metadata$`Sample File Name`)
#write.csv(data, file = "../../../Applied Machine Learning/Projects/week9/data-pooled.csv")

data2 = data %>%
  dplyr::select(-c( mz,mzmin  ,  mzmax   ,     rt ,    rtmin,     rtmax))
write.csv(data2, file = "../../../Applied Machine Learning/Projects/week9/data2.csv")

write.csv(new_metadata, "../../../Applied Machine Learning/Projects/week9/new_metadata-pooled.csv")

```








